In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data_cardiovascular_risk.csv')
data.head()

id  age  education sex is_smoking  cigsPerDay  BPMeds  prevalentStroke  \
0   0   64        2.0   F        YES         3.0     0.0                0   
1   1   36        4.0   M         NO         0.0     0.0                0   
2   2   46        1.0   F        YES        10.0     0.0                0   
3   3   50        1.0   M        YES        20.0     0.0                0   
4   4   64        1.0   F        YES        30.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    221.0  148.0   85.0    NaN       90.0     80.0   
1             1         0    212.0  168.0   98.0  29.77       72.0     75.0   
2             0         0    250.0  116.0   71.0  20.35       88.0     94.0   
3             1         0    233.0  158.0   88.0  28.26       68.0     94.0   
4             0         0    241.0  136.5   85.0  26.42       70.0     77.0   

   TenYearCHD  
0           1  
1           0  
2           0  
3           1  
4           0

In [3]:
data.rename(columns={'age': 'edad', 'education':'educacion', 'sex':'sexo', 'is_smoking':'fumador', 'cigsPerDay':'cigarrillos_por_dia','BPMeds':'toma_medicamentos_pre_art','prevalentStroke':'derrame_cerebral','prevalentHyp':'hipertenso','diabetes':'diabetico','totChol':'colesterol_total','sysBP':'presion_sistolica','diaBP':'presion_diastolica','BMI':'indice_masa_corporal','heartRate':'ritmo_cardiaco','glucose':'glucosa','TenYearCHD':'riesgo_cardiovascular_10_anios'}, inplace=True)
data.head()

id  edad  educacion sexo fumador  cigarrillos_por_dia  \
0   0    64        2.0    F     YES                  3.0   
1   1    36        4.0    M      NO                  0.0   
2   2    46        1.0    F     YES                 10.0   
3   3    50        1.0    M     YES                 20.0   
4   4    64        1.0    F     YES                 30.0   

   toma_medicamentos_pre_art  derrame_cerebral  hipertenso  diabetico  \
0                        0.0                 0           0          0   
1                        0.0                 0           1          0   
2                        0.0                 0           0          0   
3                        0.0                 0           1          0   
4                        0.0                 0           0          0   

   colesterol_total  presion_sistolica  presion_diastolica  \
0             221.0              148.0                85.0   
1             212.0              168.0                98.0   
2             250.0              116.0                71.0   
3             233.0              158.0                88.0   
4             241.0              136.5                85.0   

   indice_masa_corporal  ritmo_cardiaco  glucosa  \
0                   NaN            90.0     80.0   
1                 29.77            72.0     75.0   
2                 20.35            88.0     94.0   
3                 28.26            68.0     94.0   
4                 26.42            70.0     77.0   

   riesgo_cardiovascular_10_anios  
0                               1  
1                               0  
2                               0  
3                               1  
4                               0

In [4]:
data.to_csv('data_cardiovascular_risk_v2.csv', index=False)

In [5]:
data.shape

(3390, 17)

In [6]:
data.dtypes

id                                  int64
edad                                int64
educacion                         float64
sexo                               object
fumador                            object
cigarrillos_por_dia               float64
toma_medicamentos_pre_art         float64
derrame_cerebral                    int64
hipertenso                          int64
diabetico                           int64
colesterol_total                  float64
presion_sistolica                 float64
presion_diastolica                float64
indice_masa_corporal              float64
ritmo_cardiaco                    float64
glucosa                           float64
riesgo_cardiovascular_10_anios      int64
dtype: object

In [7]:
data.isnull()

id   edad  educacion   sexo  fumador  cigarrillos_por_dia  \
0     False  False      False  False    False                False   
1     False  False      False  False    False                False   
2     False  False      False  False    False                False   
3     False  False      False  False    False                False   
4     False  False      False  False    False                False   
...     ...    ...        ...    ...      ...                  ...   
3385  False  False      False  False    False                False   
3386  False  False      False  False    False                False   
3387  False  False      False  False    False                False   
3388  False  False      False  False    False                False   
3389  False  False      False  False    False                False   

      toma_medicamentos_pre_art  derrame_cerebral  hipertenso  diabetico  \
0                         False             False       False      False   
1                         False             False       False      False   
2                         False             False       False      False   
3                         False             False       False      False   
4                         False             False       False      False   
...                         ...               ...         ...        ...   
3385                      False             False       False      False   
3386                      False             False       False      False   
3387                      False             False       False      False   
3388                       True             False       False      False   
3389                      False             False       False      False   

      colesterol_total  presion_sistolica  presion_diastolica  \
0                False              False               False   
1                False              False               False   
2                False              False               False   
3                False              False               False   
4                False              False               False   
...                ...                ...                 ...   
3385             False              False               False   
3386             False              False               False   
3387             False              False               False   
3388             False              False               False   
3389             False              False               False   

      indice_masa_corporal  ritmo_cardiaco  glucosa  \
0                     True           False    False   
1                    False           False    False   
2                    False           False    False   
3                    False           False    False   
4                    False           False    False   
...                    ...             ...      ...   
3385                 False           False    False   
3386                 False           False    False   
3387                 False           False    False   
3388                 False           False    False   
3389                 False           False    False   

      riesgo_cardiovascular_10_anios  
0                              False  
1                              False  
2                              False  
3                              False  
4                              False  
...                              ...  
3385                           False  
3386                           False  
3387                           False  
3388                           False  
3389                           False  

[3390 rows x 17 columns]

In [8]:
filas_con_nulos = data[data.isnull().any(axis=1)] #Verifica en cada fila, si hay alguna columna con un valor null
filas_con_nulos.to_csv('rows_with_nulls.csv', index=False)
filas_con_nulos

id  edad  educacion sexo fumador  cigarrillos_por_dia  \
0        0    64        2.0    F     YES                  3.0   
8        8    41        2.0    F     YES                 20.0   
9        9    55        2.0    F      NO                  0.0   
10      10    61        1.0    F      NO                  0.0   
36      36    46        3.0    F      NO                  0.0   
...    ...   ...        ...  ...     ...                  ...   
3349  3349    46        2.0    F      NO                  0.0   
3370  3370    46        1.0    F     YES                 30.0   
3378  3378    39        3.0    F     YES                  NaN   
3379  3379    39        1.0    M     YES                 30.0   
3388  3388    60        1.0    M      NO                  0.0   

      toma_medicamentos_pre_art  derrame_cerebral  hipertenso  diabetico  \
0                           0.0                 0           0          0   
8                           NaN                 0           0          0   
9                           0.0                 0           1          0   
10                          0.0                 0           1          0   
36                          0.0                 0           0          0   
...                         ...               ...         ...        ...   
3349                        0.0                 0           0          0   
3370                        0.0                 0           0          0   
3378                        0.0                 0           0          0   
3379                        0.0                 0           0          0   
3388                        NaN                 0           1          0   

      colesterol_total  presion_sistolica  presion_diastolica  \
0                221.0              148.0                85.0   
8                220.0              126.0                78.0   
9                326.0              144.0                81.0   
10                 NaN              185.0               121.0   
36               193.0              106.5                70.5   
...                ...                ...                 ...   
3349             242.0              129.0                85.0   
3370             219.0              107.0                69.0   
3378             197.0              126.5                76.5   
3379             292.0              120.0                85.0   
3388             191.0              167.0               105.0   

      indice_masa_corporal  ritmo_cardiaco  glucosa  \
0                      NaN            90.0     80.0   
8                    20.70            86.0     79.0   
9                    25.71            85.0      NaN   
10                   35.22            80.0      NaN   
36                   26.18            75.0      NaN   
...                    ...             ...      ...   
3349                 27.40            80.0      NaN   
3370                 21.40            66.0      NaN   
3378                 19.71            55.0     63.0   
3379                 31.09            85.0      NaN   
3388                 23.01            80.0     85.0   

      riesgo_cardiovascular_10_anios  
0                                  1  
8                                  0  
9                                  0  
10                                 0  
36                                 0  
...                              ...  
3349                               1  
3370                               0  
3378                               0  
3379                               0  
3388                               0  

[463 rows x 17 columns]

In [9]:
columnas_con_nulos = data.columns[data.isnull().any()].tolist()
print("Columnas con valores nulos:")
print(columnas_con_nulos)

Columnas con valores nulos:
['educacion', 'cigarrillos_por_dia', 'toma_medicamentos_pre_art', 'colesterol_total', 'indice_masa_corporal', 'ritmo_cardiaco', 'glucosa']


**Rellenado de NaN**

Vamos a rellenar los NaN utilizando la libreria Numpy. La logica que decidimos llevar es la de agrupar por sexo y edad, ya que son campos que consdieramos suficientemente representativos para tomar el promedio, cuyo valor es el que se va a reemplazar en el campo correspondiente a

In [10]:
promedios_por_grupo = data.groupby(['sexo', 'edad'])['cigarrillos_por_dia'].transform('mean').fillna(0).astype(int)
data['cigarrillos_por_dia'].fillna(promedios_por_grupo, inplace=True)


In [11]:
promedios_por_grupo = data.groupby(['sexo', 'edad'])['colesterol_total'].transform('mean').fillna(0).astype(int)
data['colesterol_total'].fillna(promedios_por_grupo, inplace=True)

In [12]:
promedios_por_grupo = data.groupby(['sexo', 'edad'])['indice_masa_corporal'].transform('mean').fillna(0).astype(int)
data['indice_masa_corporal'].fillna(promedios_por_grupo, inplace=True)

In [13]:
promedios_por_grupo = data.groupby(['sexo', 'edad'])['ritmo_cardiaco'].transform('mean').fillna(0).astype(int)
data['ritmo_cardiaco'].fillna(promedios_por_grupo, inplace=True)

In [14]:
promedios_por_grupo = data.groupby(['sexo', 'edad'])['glucosa'].transform('mean').fillna(0).astype(int)
data['glucosa'].fillna(promedios_por_grupo, inplace=True)

In [15]:
promedios_por_grupo = data.groupby(['sexo', 'edad'])['educacion'].transform('mean').fillna(0).astype(int)
data['educacion'].fillna(promedios_por_grupo, inplace=True)

In [16]:
promedios_por_grupo = data.groupby(['sexo', 'edad'])['toma_medicamentos_pre_art'].transform(lambda x: 0 if (x == 0).sum() >= (x == 1).sum() else 1).fillna(0).astype(int)
data['toma_medicamentos_pre_art'].fillna(promedios_por_grupo, inplace=True)
data.head(10)

id  edad  educacion sexo fumador  cigarrillos_por_dia  \
0   0    64        2.0    F     YES                  3.0   
1   1    36        4.0    M      NO                  0.0   
2   2    46        1.0    F     YES                 10.0   
3   3    50        1.0    M     YES                 20.0   
4   4    64        1.0    F     YES                 30.0   
5   5    61        3.0    F      NO                  0.0   
6   6    61        1.0    M      NO                  0.0   
7   7    36        4.0    M     YES                 35.0   
8   8    41        2.0    F     YES                 20.0   
9   9    55        2.0    F      NO                  0.0   

   toma_medicamentos_pre_art  derrame_cerebral  hipertenso  diabetico  \
0                        0.0                 0           0          0   
1                        0.0                 0           1          0   
2                        0.0                 0           0          0   
3                        0.0                 0           1          0   
4                        0.0                 0           0          0   
5                        0.0                 0           1          0   
6                        0.0                 0           1          0   
7                        0.0                 0           0          0   
8                        0.0                 0           0          0   
9                        0.0                 0           1          0   

   colesterol_total  presion_sistolica  presion_diastolica  \
0             221.0              148.0                85.0   
1             212.0              168.0                98.0   
2             250.0              116.0                71.0   
3             233.0              158.0                88.0   
4             241.0              136.5                85.0   
5             272.0              182.0               121.0   
6             238.0              232.0               136.0   
7             295.0              102.0                68.0   
8             220.0              126.0                78.0   
9             326.0              144.0                81.0   

   indice_masa_corporal  ritmo_cardiaco  glucosa  \
0                 26.00            90.0     80.0   
1                 29.77            72.0     75.0   
2                 20.35            88.0     94.0   
3                 28.26            68.0     94.0   
4                 26.42            70.0     77.0   
5                 32.80            85.0     65.0   
6                 24.83            75.0     79.0   
7                 28.15            60.0     63.0   
8                 20.70            86.0     79.0   
9                 25.71            85.0     82.0   

   riesgo_cardiovascular_10_anios  
0                               1  
1                               0  
2                               0  
3                               1  
4                               0  
5                               1  
6                               0  
7                               0  
8                               0  
9                               0

In [17]:
data.to_csv('data_completa.csv', index=False)

### Estandarización de Atributos


Aqui tratamos la estadarización de atributos de la columna sexo, intercambiando M por 1 y F por 0, tambien tratamos la columna fumador dondes intercambiamos un YES por un 1 y un NO por un 0.


In [18]:
data['sexo'] = data['sexo'].replace({'M': 1, 'F': 0})
data['fumador'] = data['fumador'].replace({'YES': 1, 'NO': 0})

In [19]:
data.to_csv('DataFinal.csv', index=False)

Chequeamos que no haya ningun valor NaN en todo el DF

In [20]:
columnas_con_nulos_test = data.columns[data.isnull().any()].tolist()
print("Columnas con valores nulos:")
print(columnas_con_nulos_test)

Columnas con valores nulos:
[]


In [21]:
variable=data.to_numpy()
variable

array([[0.000e+00, 6.400e+01, 2.000e+00, ..., 9.000e+01, 8.000e+01,
        1.000e+00],
       [1.000e+00, 3.600e+01, 4.000e+00, ..., 7.200e+01, 7.500e+01,
        0.000e+00],
       [2.000e+00, 4.600e+01, 1.000e+00, ..., 8.800e+01, 9.400e+01,
        0.000e+00],
       ...,
       [3.387e+03, 4.400e+01, 3.000e+00, ..., 7.300e+01, 7.200e+01,
        1.000e+00],
       [3.388e+03, 6.000e+01, 1.000e+00, ..., 8.000e+01, 8.500e+01,
        0.000e+00],
       [3.389e+03, 5.400e+01, 3.000e+00, ..., 7.900e+01, 9.200e+01,
        0.000e+00]])

In [22]:
divisor = int(variable.shape[0] * 0.70)
divisor

2373

In [23]:
matriz_clases = variable[:, -1]
matriz_clases


array([1., 0., 0., ..., 1., 0., 0.])

In [24]:
matriz_atributos = variable [:, 1:-1]
matriz_atributos

array([[64.  ,  2.  ,  0.  , ..., 26.  , 90.  , 80.  ],
       [36.  ,  4.  ,  1.  , ..., 29.77, 72.  , 75.  ],
       [46.  ,  1.  ,  0.  , ..., 20.35, 88.  , 94.  ],
       ...,
       [44.  ,  3.  ,  1.  , ..., 28.92, 73.  , 72.  ],
       [60.  ,  1.  ,  1.  , ..., 23.01, 80.  , 85.  ],
       [54.  ,  3.  ,  0.  , ..., 29.88, 79.  , 92.  ]])

In [25]:
matriz_clases_entrenamiento=matriz_clases[1 : divisor]
matriz_clases_entrenamiento


array([0., 0., 1., ..., 0., 0., 0.])

In [26]:
matriz_clases_prueba=matriz_clases[divisor : ]
matriz_clases_prueba

array([0., 0., 0., ..., 1., 0., 0.])

In [41]:
matriz_atributos_entrenamiento= matriz_atributos [1 : divisor]
matriz_atributos_entrenamiento[0]



array([ 36.  ,   4.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,
         0.  , 212.  , 168.  ,  98.  ,  29.77,  72.  ,  75.  ])

In [28]:
matriz_atributos_test=matriz_atributos[ divisor : ]
matriz_atributos_test

array([[40.  ,  2.  ,  0.  , ..., 19.98, 96.  , 76.  ],
       [64.  ,  2.  ,  1.  , ..., 23.64, 68.  , 75.  ],
       [55.  ,  3.  ,  0.  , ..., 21.05, 72.  , 74.  ],
       ...,
       [44.  ,  3.  ,  1.  , ..., 28.92, 73.  , 72.  ],
       [60.  ,  1.  ,  1.  , ..., 23.01, 80.  , 85.  ],
       [54.  ,  3.  ,  0.  , ..., 29.88, 79.  , 92.  ]])

In [30]:
from KNN2 import KNN

In [31]:
KNN = KNN(k=3)

In [32]:
KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)

In [34]:
Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,1)

In [35]:
from sklearn.metrics import accuracy_score
precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
print("Precisión del modelo:\n",  precision)

Precisión del modelo:
 0.8328416912487709


In [ ]:
# from KNN import KNN
# KNN = KNN(k=12)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN import KNN
# KNN = KNN(k=3000)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN as K
# KNN = K(k=3000)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,3)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=3000)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,2)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=3000)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,1)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=30)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,2)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=31)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,2)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=32)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,2)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=31)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,1)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=1)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,3)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

Pruebas de las distancias con k=21

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=21)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,1)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=21)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,2)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=21)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,3)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

Pruebas de las distancias con k=31

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=31)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,1)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=31)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,2)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=31)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,3)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

Probamos las distintas distancias con k=5.

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=5)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,1)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
# from KNN2 import KNN
# KNN = KNN(k=5)
# KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
# Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,2)
# from sklearn.metrics import accuracy_score
# precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
# print("Precisión del modelo:\n",  precision)

In [ ]:
#from KNN2 import KNN
#KNN = KNN(k=5)
#KNN.entrenar(matriz_atributos_entrenamiento, matriz_clases_entrenamiento)
#Etiquetas_Predichas=KNN.predecir(matriz_atributos_test,3)
#from sklearn.metrics import accuracy_score
#precision = accuracy_score(matriz_clases_prueba, Etiquetas_Predichas)
#print("Precisión del modelo:\n",  precision)

In [36]:
from ValidarKNN import validar_knn
validar_knn(matriz_atributos_entrenamiento,matriz_clases_entrenamiento,1)

KeyboardInterrupt: 

In [37]:
from ValidarKNN import validar_knn
validar_knn(matriz_atributos_entrenamiento,matriz_clases_entrenamiento,2)

{'valores_k': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100],
 'puntajes_promedio': [0.7552742616033755,
  0.8375527426160337,
  0.8164556962025317,
  0.8417721518987342,
  0.8312236286919831,
  0.8502109704641351,
  0.8481012658227848,
  0.8481012658227848,
  0.8523206751054853,
  0.8481012658227848,
  0.8502109704641351,
  0.8459915611814346,
  0.8502109704641351,
  0.8459915611814346,
  0.8459915611814346,
  0.8459915611814346,
  0.8459915611814346,

In [ ]:
# from ValidarKNN import validar_knn
# validar_knn(matriz_atributos_entrenamiento,matriz_clases_entrenamiento,3)

{'valores_k': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40],
 'puntajes_promedio': [0.770042194092827,
  0.8333333333333334,
  0.8248945147679325,
  0.8375527426160337,
  0.8270042194092827,
  0.8375527426160337,
  0.8333333333333334,
  0.8333333333333334,
  0.8333333333333334,
  0.8396624472573839,
  0.8375527426160337,
  0.8417721518987342,
  0.8417721518987342,
  0.8417721518987342,
  0.8417721518987342,
  0.8417721518987342,
  0.8417721518987342,
  0.8438818565400844,
  0.8417721518987342,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.8438818565400844,
  0.84388

In [ ]:
from ValidarKNN import validar_knn
validar_knn(matriz_atributos_entrenamiento,matriz_clases_entrenamiento,2)